Data Science Homework 1
================
Charlotte Fowler
9/12/2019

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.2.1 ──

    ## ✔ ggplot2 3.2.1     ✔ purrr   0.3.2
    ## ✔ tibble  2.1.3     ✔ dplyr   0.8.3
    ## ✔ tidyr   0.8.3     ✔ stringr 1.4.0
    ## ✔ readr   1.3.1     ✔ forcats 0.4.0

    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

# Problem 1

``` r
#First, I the data frame as described in problem 1, with 4 variables.
data_frame_p1 = tibble(
  normal_sample = rnorm(8),
  normal_sample_positive = normal_sample > 0,
  vec_char = c("I", "need", "eight", "words", "to", "fill", "the", "vector"),
  vec_factor = factor(c("teal", "black", "teal", "white", "white", "teal", "black", "teal"))
)


#Now, to attempt taking the mean of each variable: 

#mean of normal sample
mean(pull(data_frame_p1, normal_sample))
```

    ## [1] -0.1998687

``` r
#mean of logical vector
mean(pull(data_frame_p1, (normal_sample_positive)))
```

    ## [1] 0.5

``` r
#mean of character vector
mean(pull(data_frame_p1, (vec_char)))
```

    ## Warning in mean.default(pull(data_frame_p1, (vec_char))): argument is not
    ## numeric or logical: returning NA

    ## [1] NA

``` r
#mean of categorical vector
mean(pull(data_frame_p1, (vec_factor)))
```

    ## Warning in mean.default(pull(data_frame_p1, (vec_factor))): argument is not
    ## numeric or logical: returning NA

    ## [1] NA

I can take the mean of the sample values and of the logical vector as
these both contain have numerical values, however I cannot take the mean
of the character nor categorical
vector.

``` r
#Applying 'as.numeric' function to logical, character, and categorical vectors
as.numeric(pull(data_frame_p1, (normal_sample_positive)))
as.numeric(pull(data_frame_p1, (vec_char)))
as.numeric(pull(data_frame_p1, (vec_factor)))
```

When applying the ‘as.numeric’ function to the logical, character, and
categorical vectors, it is not possible with the character vector. This
is becauase this vector contains abritrary elements, which R is not able
to process as anything numerical. However, in the logical vector, R can
interpret the 1 and 0 entries as plain numbers, and in the categorical
vector R can assign numerical values 1, 2, and 3 to the three
categories, alfabetically. This demonstrates how it’s possible to take
the mean of the logical vector above, as it has 1 and 0 values
associated with True and False, respectively. Additionally, it shows how
the character vector couldn’t have the mean calculated above, as it is
understood to be unrelated elements. With the categorical vector, if we
had used the ‘as.numeric’ function above before taking the mean, we
would have been able to, as R has now assigned a number to each
category.

``` r
#logical vector to numeric and multiplied
as.numeric(pull(data_frame_p1, (normal_sample_positive))) * 
  pull(data_frame_p1, (normal_sample))
```

    ## [1] 0.1085878 0.0000000 0.0000000 0.1936680 0.0000000 0.7425590 0.0000000
    ## [8] 0.7352138

``` r
#logical vector to factor, then multipled
factor(pull(data_frame_p1, (normal_sample_positive))) * 
  pull(data_frame_p1, (normal_sample))
```

    ## Warning in Ops.factor(factor(pull(data_frame_p1,
    ## (normal_sample_positive))), : '*' not meaningful for factors

    ## [1] NA NA NA NA NA NA NA NA

``` r
#logical vector to factor, then numeric, then multiplied
as.numeric(factor(pull(data_frame_p1, (normal_sample_positive)))) * 
  pull(data_frame_p1, (normal_sample))
```

    ## [1]  0.2171756 -0.1902209 -2.5595933  0.3873359 -0.2681517  1.4851179
    ## [7] -0.3610126  1.4704276

\#Problem 2

``` r
#Creating data frame as described in Problem 2
data_frame_p2 = tibble(
  x = rnorm(500),
  y = rnorm(500),
  logical_vector = x + y > 0,
  numerical_from_logical = as.numeric(logical_vector),
  factor_from_logical = factor(logical_vector)
)
```

``` r
mean(pull(data_frame_p2, x))
```

    ## [1] -0.01360788

``` r
median(pull(data_frame_p2, x))
```

    ## [1] 0.01699053

The size of the data set is 500 by 5.

For variable `x` the mean is -0.0136079, median is 0.0169905, and
standard deviation is 1.0624401. `x + y > 1` is true for 48% of cases.
